/*
 * This file was automatically generated by EvoSuite
 * Sat May 04 23:36:20 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FeatureEnvyCheck_ESTest extends FeatureEnvyCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      featureEnvyCheck0.setMax(0);
      boolean boolean0 = featureEnvyCheck0.getCount();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      boolean boolean0 = featureEnvyCheck0.getCount();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      featureEnvyCheck0.visitToken((DetailAST) null);
      assertFalse(featureEnvyCheck0.getCount());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      DetailAST detailAST0 = new DetailAST();
      // Undeclared exception!
      try { 
        featureEnvyCheck0.visitToken(detailAST0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("FeatureEnvyCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      assertFalse(featureEnvyCheck0.getCount());
      
      featureEnvyCheck0.setMax((-1513));
      boolean boolean0 = featureEnvyCheck0.getCount();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      int[] intArray0 = featureEnvyCheck0.getDefaultTokens();
      assertArrayEquals(new int[] {14}, intArray0);
      assertFalse(featureEnvyCheck0.getCount());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      int[] intArray0 = featureEnvyCheck0.getAcceptableTokens();
      assertArrayEquals(new int[] {27, 10}, intArray0);
      assertFalse(featureEnvyCheck0.getCount());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FeatureEnvyCheck featureEnvyCheck0 = new FeatureEnvyCheck();
      int[] intArray0 = featureEnvyCheck0.getRequiredTokens();
      assertEquals(0, intArray0.length);
      assertFalse(featureEnvyCheck0.getCount());
  }
}
